spring.application.name=careerflow
spring.datasource.url=jdbc:postgresql://localhost:5432/CareerFlow
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true